DSK_Clothes/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using DSK_Clothes.ConnectionDatabase;
using DSK_Clothes.Models;

namespace DSK_Clothes.Controllers
{
    public class SignUpController : Controller
    {
        ConnectUser cnu = new ConnectUser();
        //
        // GET: /SignUp/

        //-------
        //------------------------------------------------ ACTION SIGN UP
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(User u)
        {
            bool kt = false;
            try
            {
                if (ModelState.IsValid)
                {
                    kt = cnu.createAccount(u);
                    if (kt)
                    {
                        TempData["MessageSuccess"] = "Đăng ký tài khoản thành công!";
                    }
                    else
                    {
                        TempData["MessageError"] = "Đăng ký tài khoản thất bại! Do số điện thoại " + u.Tel + " đã được đăng ký rồi!";
                    }
                }
                return View();
            }
            catch (Exception e)
            {
                TempData["MessageError"] = e.Message;
                return View();
            }
        }

        //-------
        //------------------------------------------------ ACTION LOG IN
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string Tel, string Password)
        {
            bool kt = false;
            var listUser = cnu.getAllUser();
            try
            {
                if (Tel != string.Empty && Password != string.Empty)
                {
                    kt = cnu.loginAccount(Tel);
                    if (kt)
                    {
                        foreach (var item in listUser)
                        {
                            if (Tel == item.Tel && Password == item.Password)
                            {
                                if (item.MaQuyen == 1)
                                {
                                    return RedirectToAction("Home", "Home");
                                }
                                else
                                {
                                    return RedirectToAction("HomeOfEmp", "HomeOfEmp");
                                }
                            }
                            if (Tel == item.Tel && Password != item.Password)
                            {
                                TempData["MessageError"] = "Mật khẩu sai, vui lòng thử lại!";
                                return View();
                            }
                        }
                    }
                }
                else
                {
                    TempData["MessageError"] = "Vui lòng điền đầy đủ thông tin!";
                }
                return View();
            }
            catch
            {
                TempData["MessageError"] = "Số điện thoại " + Tel + " của bạn chưa được đăng ký trên trang web này!";
                return View();
            }
        }
    }
}

DSK_Clothes/Views/SignUp/LogIn.cshtml
@{
    ViewBag.Title = "LogIn";    
}
@model DSK_Clothes.Models.User

@*---------------
------------------------------------- HEADER *@
@Html.Partial("HeaderNavbar", "Shared")

<main class="main">
    <div class="form-su">
        <div class="header_form">ĐĂNG NHẬP</div>
        <div class="info_alert">
            @if (TempData["MessageError"] != null)
            {
                <div class="alert alert-danger fade show" role="alert">
                    <strong>Thông báo: </strong> @TempData["MessageError"]
                </div>
            }
        </div>
        <div class="su-link">
            "Bạn chưa có tài khoản?"
            @Html.ActionLink("Đăng ký", "SignUp", "SignUp", new { @class="form__link"})
        </div>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)
            <form>
                <div class="body_form">
                    <div class="input_form">
                        @Html.TextBoxFor(p => p.Tel, new { @type = "tel", @class = "rs-form form__inp", @placeholder = "Số điện thoại" })
                        @Html.ValidationMessageFor(p => p.Tel, "", new { @class = "text-danger" })
                    </div>
                    <div class="input_form">
                        @Html.TextBoxFor(p => p.Password, new { @type = "password", @class = "rs-form form__inp", @placeholder = "Mật khẩu" })
                        @Html.ValidationMessageFor(p => p.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="box">
                        <div class="item">
                            <div class="checkbox-rect2">
                                <input type="checkbox" id="checkbox-rect2" name="check">
                                <label for="checkbox-rect2">Ghi nhớ tài khoản</label>
                            </div>
                        </div>
                    </div>
                    <div class="btn-cre fl-wrap mr-b">
                        <div class="fg-ps">
                            <a href="#">Quên mật khẩu</a>
                        </div>
                        <div class="submit__btn">
                            <button type="submit" class="btn-dark unlock-btn">Đăng nhập</button>
                        </div>
                    </div>
                    <p class="text-danger danger-mb">@ViewBag.Message</p>  
                </div>
            </form>
        }
    </div>
</main>

DSK_Clothes/Views/SignUp/SignUp.cshtml
@{
    ViewBag.Title = "Register";
}

@model DSK_Clothes.Models.User

@*---------------
------------------------------------- HEADER *@
@Html.Partial("HeaderNavbar", "Shared")

<main class="main">
    <div class="form-su">
        <div class="header_form">TẠO TÀI KHOẢN</div>
        <div class="info_alert">
            @if (TempData["MessageSuccess"] != null)
            {
                <div class="alert alert-success fade show" role="alert">
                    <strong>Thông báo: </strong> @TempData["MessageSuccess"] bấm @Html.ActionLink("vào đây", "LogIn", "SignUp") để chuyển sang trang Login!
                </div>
            }
            @if (TempData["MessageError"] != null)
            {
                <div class="alert alert-danger fade show" role="alert">
                    <strong>Thông báo: </strong> @TempData["MessageError"]
                </div>
            }
        </div>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)
            <form>
                <div class="body_form">
                    <div class="input_form">
                        @Html.TextBoxFor(p => p.FullName, new { @type = "text", @class = "rs-form form__inp", @placeholder = "Họ và tên" })
                        @Html.ValidationMessageFor(p => p.FullName, "", new { @class = "text-danger" })
                        <p class="help-block">Nhập họ tên đầy đủ, Capital từng từ!</p>
                    </div>
                    <div class="input_form">
                        @Html.TextBoxFor(p => p.Email, new { @type = "email", @class = "rs-form form__inp", @placeholder = "Email" })
                        @Html.ValidationMessageFor(p => p.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="input_form">
                        @Html.TextBoxFor(p => p.Tel, new { @type = "tel", @class = "rs-form form__inp", @placeholder = "Số điện thoại" })
                        @Html.ValidationMessageFor(p => p.Tel, "", new { @class = "text-danger" })
                    </div>
                    <div class="input_form">
                        @Html.TextBoxFor(p => p.BirthDay, new { @type = "date", @class = "rs-form form__inp", @placeholder = "Ngày sinh" })
                        @Html.ValidationMessageFor(p => p.BirthDay, "", new { @class = "text-danger" })
                    </div>
                    <div class="input_form">
                        @Html.TextBoxFor(p => p.Password, new { @type = "password", @class = "rs-form form__inp", @placeholder = "Mật khẩu" })
                        @Html.ValidationMessageFor(p => p.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="input_form">
                        @Html.TextBoxFor(p => p.ConfirmPassword, new { @type = "password", @class = "rs-form form__inp", @placeholder = "Xác nhận mật khẩu" })
                        @Html.ValidationMessageFor(p => p.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                    <div class="box">
                        <div class="item">
                            <div class="checkbox-rect2">
                                <input type="checkbox" id="chkbox" name="check" onclick="unlock_btn()">
                                <label for="chkbox">Tôi đồng ý với các điều khoản và điều kiện, chính sách bảo mật và chính sách cookie</label>
                            </div>
                        </div>
                    </div>
                    <div class="btn-cre mr-b">
                        <button type="submit" id="btn-create" class="btn-dark btn-nor" disabled>Tạo</button>
                    </div>
                    <div class="footer_form">
                        <p>Nếu sdt hoặc email của bạn báo đã tồn tại, bấm @Html.ActionLink("vào đây", "LogIn", "SignUp") và login với sdt hoặc email đó với một mật khẩu bất kì để kích hoạt tài khoản hoặc liên hệ với bộ phận cskh của DSK CLOTHES để được hỗ trợ</p>
                    </div>
                </div>
            </form>
        }
    </div>    
</main>